plugins {
	id 'java'
}

group = 'com.viameowts.viastyle'
version = '1.0.0'
base.archivesName = 'viastyle-velocity'

repositories {
	maven { url 'https://repo.papermc.io/repository/maven-public/' }
	mavenCentral()
}

dependencies {
	compileOnly 'com.velocitypowered:velocity-api:4.2.0'
	annotationProcessor 'com.velocitypowered:velocity-api:4.2.0'
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release.set(25)
}
